//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otel4
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Классы.
    /// </summary>
    // *** Start programmer edit section *** (Классы CustomAttributes)

    // *** End programmer edit section *** (Классы CustomAttributes)
    public enum Классы
    {
        
        // *** Start programmer edit section *** (Классы.1 CustomAttributes)

        // *** End programmer edit section *** (Классы.1 CustomAttributes)
        1,
        
        // *** Start programmer edit section *** (Классы.2 CustomAttributes)

        // *** End programmer edit section *** (Классы.2 CustomAttributes)
        2,
        
        // *** Start programmer edit section *** (Классы.3 CustomAttributes)

        // *** End programmer edit section *** (Классы.3 CustomAttributes)
        3,
        
        // *** Start programmer edit section *** (Классы.4 CustomAttributes)

        // *** End programmer edit section *** (Классы.4 CustomAttributes)
        4,
        
        // *** Start programmer edit section *** (Классы.5 CustomAttributes)

        // *** End programmer edit section *** (Классы.5 CustomAttributes)
        5,
    }
}
