//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otel4
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Места.
    /// </summary>
    // *** Start programmer edit section *** (Места CustomAttributes)

    // *** End programmer edit section *** (Места CustomAttributes)
    public enum Места
    {
        
        // *** Start programmer edit section *** (Места.1 CustomAttributes)

        // *** End programmer edit section *** (Места.1 CustomAttributes)
        1,
        
        // *** Start programmer edit section *** (Места.2 CustomAttributes)

        // *** End programmer edit section *** (Места.2 CustomAttributes)
        2,
        
        // *** Start programmer edit section *** (Места.3 CustomAttributes)

        // *** End programmer edit section *** (Места.3 CustomAttributes)
        3,
        
        // *** Start programmer edit section *** (Места.4 CustomAttributes)

        // *** End programmer edit section *** (Места.4 CustomAttributes)
        4,
        
        // *** Start programmer edit section *** (Места.5 CustomAttributes)

        // *** End programmer edit section *** (Места.5 CustomAttributes)
        5,
    }
}
